namespace :api_types do
  task generate: :environment do
    definition = ArSerializer::TypeScript.generate_type_definition ApiController::RootObject
    comment = '// auto generated by `rake api_types:generate`'
    File.write Rails.root.join('client', 'api/types.ts'), comment + "\n" + definition
  end
end
